---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-12T02:13:23Z"
  name: carts-canary
  resourceVersion: "1141011"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: f96c74b0-1c84-11ea-8ef8-42010a980fc9
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
